[package]
name = "atri-elo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tera = "1"
tokio = { version = "1", features = ["full"] }
axum = "0.5"
lazy_static = "1"
dotenv_codegen = "0.15"
libmdbx = "0.1"
speedy = "0.8"
chrono = "0.4"
